
name: 'oss_data_platform'
version: '1.0.0'
config-version: 2

profile: 'oss_data_platform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by 'dbt clean'
  - "target"
  - "dbt_packages"

models:
  oss_data_platform:
    # Config for all models in the project
    materialized: view 
